select * from customer

-- total revenue generated by male vs female

select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- avg purchase amount used a discount but still spent more

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- top 5 product with highest avg rating

select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- avg puchase amount btw standard and express shipping

select shipping_type,
Round(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- do subscriber spent more

select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


-- 5 produts have the high percentage of purchases with discount applied

select item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;